#!/usr/bin/env ruby
# frozen_string_literal: true

require 'cmdparse'
require 'ptimelog'

parser = CmdParse::CommandParser.new(handle_exceptions: true)
parser.main_options.version = Ptimelog::VERSION
parser.main_options.program_name = 'ptimelog'
parser.main_options.banner = Ptimelog::BANNER

parser.add_command(CmdParse::VersionCommand.new)
parser.add_command(CmdParse::HelpCommand.new, default: true)
parser.add_command(Ptimelog::Command::Info.new)

parser.add_command(Ptimelog::Command::Add.new)
parser.add_command(Ptimelog::Command::Edit.new)
parser.add_command(Ptimelog::Command::Show.new)
parser.add_command(Ptimelog::Command::Upload.new)
parser.add_command(Ptimelog::Command::Confirm.new)

begin
  parser.parse
rescue Ptimelog::Error => e
  warn <<~MSG
    An Error occured: #{e.class}

    #{e.message}
  MSG
end
